#!/bin/sh
# meshflare WireGuard extractor — our reimplementation of the wgcf-connector flow.
# Expects CONNECTOR_TOKEN in the environment; writes conf to stdout or /tmp/wg.conf
set -eu

TOKEN="${CONNECTOR_TOKEN:-}"
if [ -z "$TOKEN" ]; then
  echo "CONNECTOR_TOKEN required" >&2
  exit 1
fi

dbus-daemon --system
/bin/warp-svc >/tmp/warp-svc.log 2>&1 &
sleep 5

warp-cli --accept-tos connector new "$TOKEN"
sleep 5

REG=/var/lib/cloudflare-warp/reg.json
CONF=/var/lib/cloudflare-warp/conf.json

PUBKEY=$(jq -r .public_key < "$CONF")
EXPECTED="bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
if [ "$PUBKEY" != "$EXPECTED" ]; then
  echo "Error: Got MASQUE instead of WireGuard. Set the device profile tunnel protocol to WireGuard." >&2
  exit 1
fi

OUT=/tmp/wg.conf
cat > "$OUT" <<EOL
# Registration ID: $(jq -r .registration_id[0] < "$REG")
# Organization: $(jq -r .account.organization < "$CONF")
# Generated by meshflare
[Interface]
PrivateKey = $(jq -r .secret_key < "$REG")
Address = $(jq -r .interface.v6 < "$CONF")/128, $(jq -r .interface.v4 < "$CONF")/32
DNS = 2606:4700:4700::1111, 2606:4700:4700::1001, 1.1.1.1, 1.0.0.1
MTU = 1420

[Peer]
PublicKey = $PUBKEY
AllowedIPs = ::/0, 0.0.0.0/0
Endpoint = $(jq -r .endpoints[0].v4 < "$CONF")
EOL

cat "$OUT"
