#!/bin/sh
# Local WireGuard conf extraction via warp-cli (same flow as former meshflare-wg).
# Expects CONNECTOR_TOKEN in the environment; prints .conf to stdout.
set -eu

TOKEN="${CONNECTOR_TOKEN:-}"
if [ -z "$TOKEN" ]; then
  echo "CONNECTOR_TOKEN required" >&2
  exit 1
fi

if ! command -v warp-cli >/dev/null 2>&1; then
  echo "warp-cli not installed (WireGuard extract requires the meshflare Docker image)" >&2
  exit 1
fi

mkdir -p /run/dbus /tmp

if ! pgrep -x dbus-daemon >/dev/null 2>&1; then
  dbus-daemon --system || true
fi

# Long-lived container: clear any prior enrollment before connector new.
# Wiping the data dir while warp-svc is up leaves an in-memory registration
# ("Old registration is still around").
if pgrep -x warp-svc >/dev/null 2>&1; then
  warp-cli --accept-tos disconnect >/dev/null 2>&1 || true
  warp-cli --accept-tos registration delete >/dev/null 2>&1 || true
  # Restart warp-svc so the next enroll starts from a clean process state.
  pkill -x warp-svc >/dev/null 2>&1 || true
  # Wait until the old process exits (up to ~5s).
  i=0
  while pgrep -x warp-svc >/dev/null 2>&1 && [ "$i" -lt 50 ]; do
    sleep 0.1
    i=$((i + 1))
  done
fi

rm -rf /var/lib/cloudflare-warp
mkdir -p /var/lib/cloudflare-warp

/bin/warp-svc >/tmp/warp-svc.log 2>&1 &
sleep 5

warp-cli --accept-tos connector new "$TOKEN"
sleep 5

REG=/var/lib/cloudflare-warp/reg.json
CONF=/var/lib/cloudflare-warp/conf.json

if [ ! -f "$REG" ] || [ ! -f "$CONF" ]; then
  echo "warp registration files missing; see /tmp/warp-svc.log" >&2
  exit 1
fi

PUBKEY=$(jq -r .public_key < "$CONF")
EXPECTED="bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
if [ "$PUBKEY" != "$EXPECTED" ]; then
  echo "Error: Got MASQUE instead of WireGuard. Set the device profile tunnel protocol to WireGuard." >&2
  exit 1
fi

cat <<EOL
# Registration ID: $(jq -r .registration_id[0] < "$REG")
# Organization: $(jq -r .account.organization < "$CONF")
# Generated by meshflare
[Interface]
PrivateKey = $(jq -r .secret_key < "$REG")
Address = $(jq -r .interface.v6 < "$CONF")/128, $(jq -r .interface.v4 < "$CONF")/32
DNS = 2606:4700:4700::1111, 2606:4700:4700::1001, 1.1.1.1, 1.0.0.1
MTU = 1420

[Peer]
PublicKey = $PUBKEY
AllowedIPs = ::/0, 0.0.0.0/0
Endpoint = $(jq -r .endpoints[0].v4 < "$CONF")
EOL
